config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  get 'search', to: "flats#search"

  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.search(params[:search])
  end
  def show
    @flat = Flat.find(params[:id])
  end
  def new
    @flat = Flat.new
  end
  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end
  def edit
    @flat = Flat.find(params[:id])
  end
  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :edit
    end
  end
  def destroy
    @flat = Flat.find(params[:id])

    @flat.destroy
    redirect_to flats_path
  end




  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :description, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mainconte">
  <h1>Edit
    <%= @flat.name %>
  </h1>
  <%= simple_form_for @flat do |f| %>
  <div id="formholder">
    <%= f.input :name, :class => "form-group" %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <div class="btngroup d-flex">
      <%= f.button :submit, :class => "btn btn-primary mr-3 mb-3"  %>
      <% end %>
      <%= link_to "Cancel", flats_path, class: "btn btn-danger mb-3" %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="main">
  <h1 class="display-6">All our flats</h1>
  <p> All
    <%= @flats.count %> Flats </p>
</div>
<div class="gird-container container mt-3">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="carder">
        <img src="https://source.unsplash.com/random/1200x400">
        <div class="flat-contents">
          <p><strong>
              <%= flat.name %></strong></p>
          <p>
            <%= flat.address %>
          </p>
          <div class="bottom-icons">
            <i class="fas fa-user-friends"></i>
            <p style="margin-right: 30px;">
              <%= flat.number_of_guests %>
            </p>
            <i class="fas fa-euro-sign"></i>
            <p>
              <%= flat.price_per_night %>
            </p>
          </div>
        </div>
        <div class="footy">
          <%= link_to "More Info", flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat), style: "color: #FFC007"%>
          <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure you want to delete this listing" }, style: "color: #E04856" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mainconte">
  <h1>Add a new flat</h1>
  <%= simple_form_for @flat do |f| %>
  <div id="formholder">
    <%= f.input :name, :class => "form-group" %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <div class="btngroup d-flex">
      <%= f.button :submit, :class => "btn btn-primary mr-3 mb-3"  %>
      <% end %>
      <%= link_to "Cancel", flats_path, class: "btn btn-danger mb-3" %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
<div class="container margin-top-negative main-cont">
  <div class="row">
    <div class="col-8">
      <div class="top-card">
        <h1 class="display-5">
          <%= @flat.name %>
        </h1>
        <p>
          <%= @flat.address %>
        </p>
      </div>
      <div class="below-card">
        <h2> A bit more about this flat</h2>
        <p>
          <%= @flat.description %>
        </p>
      </div>
    </div>
    <div class="col-4">
      <div class="book-place">
        <p><strong>Book This Place!</strong></p>
        <div class="input-group mb-2">
          <span class="input-group-text" id="basic-addon1">From:</span>
          <input type="text" class="form-control" placeholder="02/15/2021" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-2">
          <span class="input-group-text" id="basic-addon1">To:</span>
          <input type="text" class="form-control" placeholder="03/12/2021" aria-label="Username" aria-describedby="basic-addon1">
        </div>
        <button type="button" class="btn btn-success bottom-btn1">Book</button>
      </div>
      <div class="details">
        <h2><strong>Details</strong></h2>
        <div class="d-flex">
          <div class="d-flex"><i class="fas fa-user-friends mr-2"></i>
            <p style="margin-right: 30px;">
              <%= @flat.number_of_guests %>
            </p>
          </div>
          <div class="d-flex"><i class="fas fa-euro-sign mr-2"></i>
            <p>
              <%= @flat.price_per_night %>
            </p>
          </div>
        </div>
      </div>
      <div class="socials">
        <div class="flex-align">
          <p>Share</p>
          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x mr-3"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsSimpleAirbnb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= yield %>
</body>

</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <%= link_to "Simple AirBnB", flats_path, class: "navbar-brand" %>
    <div class="d-flex">
      <%= form_tag flats_path, :method => 'get', :class => "d-flex" do  %>
      <%= text_field_tag :search, params[:search], :class => "form-control me-2", :style => "margin-right: 10px;" %>
      <%= submit_tag "Search", :class => "btn btn-outline-success btnnav", :style => "margin-right: 10px" %>
      <%= link_to  "Add Flat", new_flat_path, class: "btn btn-outline-primary btnnav", type: "submit" %>
    </div>
  </div>
</nav>
<% end %>